components:
  default:
    merge_strategy: "group_1"
    auto_merge: true
    auto_label: true

  libsahtrace:
    merge_strategy: "individual"

build:

  whitelist:
  - "container-cortexa7"
  - "container-cortexa53"

  linked:
  - layer: "meta-amx"
