# We have a conf and classes directory, add to BBPATH
BBPATH =. "${LAYERDIR}:"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

LICENSE_PATH += "${LAYERDIR}/licenses"

BBFILE_COLLECTIONS += "meta-usp"
BBFILE_PATTERN_meta-usp = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-usp = "6"

HOSTTOOLS:append = "fakeroot"

LAYERDEPENDS_meta-usp = "core"
LAYERSERIES_COMPAT_meta-usp = "honister"

LAYERDEPENDS_meta-usp = "meta-amx"

GIT_BASE_URL ?= "gitlab.com/soft.at.home"
